# Generated by Django 4.2.4 on 2023-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
